Update ekstrak.yml

diff --git a/.github/workflows/ekstrak.yml b/.github/workflows/ekstrak.yml
--- a/.github/workflows/ekstrak.yml
+++ b/.github/workflows/ekstrak.yml
@@ -26,8 +26,20 @@ jobs:
       - name: Unpack specified zip file to target directory
         run: unzip ${{ github.event.inputs.zip_file }} -d ${{ github.event.inputs.extract_to }}
 
+      - name: List extracted files for verification
+        run: ls -R ${{ github.event.inputs.extract_to }}
+
       - name: Remove zip file after extraction
         run: rm -f ${{ github.event.inputs.zip_file }}
+
+      - name: Confirm zip file removal
+        run: |
+          if [ -f "${{ github.event.inputs.zip_file }}" ]; then
+            echo "Error: ZIP file was not deleted"
+            exit 1
+          else
+            echo "ZIP file successfully deleted"
+          fi
 
       - name: Commit and Push Changes
         run: |
